let lessons = [

        {
            subject: 'maths',
            location: 'malta',
            price: 100,
            numberOfSpaces: 5,
            image: 'images/mathematics.jpg',
        },
        {
            subject: 'english',
            location: 'london',
            price: 50,
            numberOfSpaces: 5,
            image: 'images/english.jpg',
        },
        {
            subject: 'biology',
            location: 'mauritius',
            price: 250,
            numberOfSpaces: 5,
            image: 'images/biology.jpg',
        },
        {
            subject: 'chemistry',
            location: 'mauritius',
            price: 150,
            numberOfSpaces: 5,
            image: 'images/chemistry.jpg',
        },
        {
            subject: 'Chess',
            location: 'spain',
            price: 100,
            numberOfSpaces: 5,
            image: 'images/chess.jpg',
        },
        {
            subject: 'Poker',
            location: 'london',
            price: 200,
            numberOfSpaces: 5,
            image: 'images/poker.jpg',
        },
        {
            subject: 'French',
            location: 'dubai',
            price: 400,
            numberOfSpaces: 5,
            image: 'images/french.jpg',
        },
        {
            subject: 'Art',
            location: 'dubai',
            price: 150,
            numberOfSpaces: 5,
            image: 'images/art.jpg',
        },
        {
            subject: 'Engineering',
            location: 'malta',
            price: 300,
            numberOfSpaces: 5,
            image: 'images/engineering.jpg',
        },
        {
            subject: 'Design',
            location: 'spain',
            price: 150,
            numberOfSpaces: 5,
            image: 'images/design.png',
        },
        {
            subject: 'Spanish',
            location: 'london',
            price: 120,
            numberOfSpaces: 5,
            image: 'images/spanish.jpg',
        }
]